### ISSUE TITLE
[2.16.1] <type 'exceptions.AttributeError'> 'FieldVirtual' object has no attribute 'listable'

### ISSUE THREAD

**Issue by domezzzzx** [web2py/web2py#1815]
Version windows EXE, 2.16.1-stable+timestamp.2017.11.14.05.54.25

Error in sqlform.grid with virtual field

> File "C:\web2py_sitio\gluon\sqlhtml.py", line 2453, in grid
>     columns = [f for f in fields if f.tablename in tablenames and f.listable]
> AttributeError: 'FieldVirtual' object has no attribute 'listable'

model:
>   table familiares
>   ------------
>     Field.Virtual('famedad', lambda row: fchsDifAnios(row.familiares.famnacfch, request.now.date())[0]),

>   table afifam
>   ------------
>     Field.Virtual('afifamedad',
>                        lambda row: db(db.familiares.id==row.afifam.famid).select().first().famedad,
>                        label='edad'

In web2py 2.15.4 run ok.

**Comment by AlxG78** [comment]
same


web2py™ | Version 2.16.1-stable+timestamp.2017.11.14.05.54.25
-- | --
Python 2.7.14: /usr/bin/python2 (prefix: /usr)

**Comment by AlxG78** [comment]
Hello,

Same

--
127.0.0.1.2017-12-03.11-04-26.a0d46cc0-4ccf-45a4-bde1-63d011050959
<type 'exceptions.AttributeError'> 'FieldVirtual' object has no attribute 'listable'

web2py™ | Version 2.16.1-stable+timestamp.2017.11.14.05.54.25
-- | --
Python 2.7.14: /usr/bin/python2 (prefix: /usr)

Traceback (most recent call last):
  File "/mnt/sda6_home/codigo/tmp/w2p_test/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/mnt/sda6_home/codigo/tmp/w2p_test/web2py/applications/SgCad/controllers/default.py", line 158, in <module>
  File "/mnt/sda6_home/codigo/tmp/w2p_test/web2py/gluon/globals.py", line 419, in <lambda>
    self._caller = lambda f: f()
  File "/mnt/sda6_home/codigo/tmp/w2p_test/web2py/gluon/tools.py", line 3982, in f
    return action(*a, **b)
  File "/mnt/sda6_home/codigo/tmp/w2p_test/web2py/applications/SgCad/controllers/default.py", line 80, in index
    links=links, orderby=orderby, paginate=paginate, sortable=True, formstyle = 'table3cols', showbuttontext=False)
  File "/mnt/sda6_home/codigo/tmp/w2p_test/web2py/gluon/sqlhtml.py", line 2453, in grid
    columns = [f for f in fields if f.tablename in tablenames and f.listable]
AttributeError: 'FieldVirtual' object has no attribute 'listable'

<type 'exceptions.AttributeError'>('FieldVirtual' object has no attribute 'listable')

**Comment by icodk** [comment]
I get the same error when running under 2.16.1
<type 'exceptions.AttributeError'> 'FieldVirtual' object has no attribute 'listable'
Works fine in 2.14.06
Field definition:
db.zone.inside = Field.Virtual('inside', lambda row: 1)

**Comment by vicding** [comment]
same error here. for version 2.16.1

**Comment by damufo** [comment]
same error here. for version 2.16.1

**Comment by dartg** [comment]
This is a pyDAL issue but seems to be [already solved](https://github.com/web2py/pydal/commit/ccc4d4c7f8e9bfb285597d266489e169ecadbbfa).

**Comment by domezzzzx** [comment]
The developer windows version was downloaded (*), confirming the correction of the reported error. 
We closed the insider. Thank you

(*) Version 2.16.1-stable + timestamp.2018.06.02.04.50.21
