### ISSUE TITLE
[2.16.1] <type 'exceptions.AttributeError'> 'Field' object has no attribute 'options'

### ISSUE THREAD

**Issue by robinvandernoord** [web2py/web2py#1813]
Since I updated to 2.16 I get this error on every page (even new apps, but not admin):
```
<type 'exceptions.AttributeError'>('Field' object has no attribute 'options')

Traceback (most recent call last):
  File "/home/robin/Documents/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/robin/Documents/web2py/applications/newversion/models/db.py", line 95, in <module>
    auth.define_tables(username=False, signature=False)
  File "/home/robin/Documents/web2py/gluon/tools.py", line 2216, in define_tables
    super(Auth, self).define_tables(username, signature, migrate, fake_migrate)._table_signature_list
  File "/home/robin/Documents/web2py/gluon/authapi.py", line 350, in define_tables
    format='%(first_name)s %(last_name)s (%(id)s)'))
  File "/home/robin/.local/lib/python2.7/site-packages/pydal/base.py", line 587, in define_table
    table = self.lazy_define_table(tablename, *fields, **args)
  File "/home/robin/.local/lib/python2.7/site-packages/pydal/base.py", line 606, in lazy_define_table
    field.requires = auto_validators(field)
  File "/home/robin/.local/lib/python2.7/site-packages/pydal/helpers/methods.py", line 260, in auto_validators
    return db.validators_method(field)
  File "/home/robin/Documents/web2py/gluon/dal.py", line 35, in _default_validators
    if isinstance(field.options, list) and field.requires:
AttributeError: 'Field' object has no attribute 'options'
```

**Comment by mdipierro** [comment]
Did you upgrade web2py but not pydal?

**Comment by ridwanonchy** [comment]
kma_onchy.com

**Comment by ilvalle** [comment]
@robinvandernoord updating pydal fix the problem. would you close this issue?
