### ISSUE TITLE
@Mobilize support missing in 2.15.2?

### ISSUE THREAD

**Issue by wish7code** [web2py/web2py#1721]
After upgrading to 2.15.2 views using **mobilize** statement throw an exception.
Before (2.14.6) same views worked fine

I can reproduce this using a minimal example 

from gluon.contrib.user_agent_parser import mobilize
@mobilize
def index():
   return dict()

throws an error
<type 'exceptions.ImportError'> cannot import name mobilize

Traceback (most recent call last):

File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted
exec(ccode, environment)
File "/home/www-data/web2py/applications/myapp/controllers/stats.py", line 3, in <module>    from gluon.contrib.user_agent_parser import mobilize

ImportError: cannot import name mobilize

Any ideas?

**Comment by wish7code** [comment]
Cross ref to mailing list, a least another user confirms same issue

https://groups.google.com/d/msg/web2py/ooZKk5i8zew/2TckkMq6CAAJ

**Comment by wish7code** [comment]
Found it: mobilize was removed here:

https://github.com/web2py/web2py/commit/d9c7953147bd78bd2e3ebf546b989538ae983c8e#diff-795b1930ce8fe2b530ad43ece7532341L557

but this breaks backward compatibility and is not yet reflected in the documentation (see http://web2py.com/books/default/chapter/29/05/the-views#Mobile-development)
