### ISSUE TITLE
simplejsonrpc does not work with python3.8

### ISSUE THREAD

**Issue by iiijjjii** [web2py/web2py#2346]
In python3.8, urllib.request changed the way urllib.parse methods are imported                                                                                  
using leading underscores. As a result simplejsonrpc no longer works.
                                                                                                                                                                                                                                                        >>> from gluon.contrib.simplejsonrpc import ServerProxy                                                                                                         
>>> URL = "http://localhost:8000/app/webservice/call/jsonrpc"                                                                                                   >>> service = ServerProxy(URL, verbose=False)                                                                                                                   
AttributeError: module 'urllib.request' has no attribute 'splittype' 
                                                                                                                                                                                                                                                           
This can be fixed with this change in gluon/contrib/simplejsonrpc.py
-   import urllib.request as urllib                                                                                                                             
+   import urllib.parse as urllib
