### ISSUE TITLE
When upgrading to web2py 2.15.2 windows environment SSL support stoped working

### ISSUE THREAD

**Issue by Jhleite** [web2py/web2py#1716]
I have just upgraded to web2py 2.15.2 in windows and I use python 2.7.11 for a while now to have the latest SSL protocols and work with PayPal. I use the following command line:

C:\web2py\web2py.py -a admin -i 192.168.8.100 -p 443 -c server.crt -k server.key -Y

and now the following error appears (without changing Python configuration):

--------------------------------------------------------------------------------------------
Version 2.15.2-stable+timestamp.2017.07.19.12.18.41
Database drivers available: psycopg2, pymysql, imaplib, sqlite3, pg8000, pyodbc

please visit:
	https://192.168.8.100:443/
use "taskkill /f /pid 25308" to shutdown the web2py server

2017-08-04 17:14:35,680 - web2py - WARNING - Python "ssl" module unavailable. SSL is OFF
------------------------------------------------------------------------------------------------------------

Well if the python SSL module was available before why is it not available now in web2py 2.15.2?

**Comment by Jhleite** [comment]
If I import ssl directly in the main.py module I get the following error:

Traceback (most recent call last):
  File "C:\web2py\web2py.py", line 21, in <module>
    import gluon.widget
  File "C:\web2py\gluon\widget.py", line 26, in <module>
    from gluon import main, newcron
  File "C:\web2py\gluon\main.py", line 28, in <module>
    import ssl
  File "C:\Python27\lib\ssl.py", line 126, in <module>
    from _ssl import HAS_SNI, HAS_ECDH, HAS_NPN, HAS_ALPN
ImportError: cannot import name HAS_ALPN

**Comment by leonelcamara** [comment]
Seems like a windows python bug, are you running 2.7.13?

**Comment by Jhleite** [comment]
I have tried with 2.7.11 that was stable with the previous web2py version and then upgraded to 2.7.13 and it persisted.
But with ubuntu it is working fine with 2.7.11.

**Comment by Jhleite** [comment]
Response from Python issue:

There is no _ssl.py. The internal _ssl module is a C extension module. Under Windows it is called _ssl.pyd. Do you have a _ssl.py  or _ssl package in your project that may confict with _ssl.pyd?

**Comment by mdipierro** [comment]
fixed in #dc29f33
