### ISSUE TITLE
web2py does not work with Python 3.12

### ISSUE THREAD

**Issue by kszys** [web2py/web2py#2478]
**Describe the bug**

`imp` module has been removed in Python 3.12. This results in the following (among others) when running web2py:

```
File "/web2py/gluon/compileapp.py", line 17, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

**To Reproduce**

1. Install Python 3.12
2. Download the official release of web2py
3. Try to start it

**Expected behavior**

web2py should be compatible with current Python version.

**Comment by marc1729** [comment]
Additional Information
I ran into the same issue, here is some additional Information:
Removing the `import imp` statement lets one start web2py but this error pops up:
```
Traceback (most recent call last):
  File "C:\Users\marc\Desktop\web2py\gluon\contrib\appconfig.py", line 139, in read_config
    getattr(self, 'read_config_' + self.ctype)()
  File "C:\Users\marc\Desktop\web2py\gluon\contrib\appconfig.py", line 123, in read_config_ini
    config = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```
During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "C:\Users\marc\Desktop\web2py\gluon\main.py", line 439, in wsgibase
    serve_controller(request, response, session)
  File "C:\Users\marc\Desktop\web2py\gluon\main.py", line 173, in serve_controller
    run_models_in(environment)
  File "C:\Users\marc\Desktop\web2py\gluon\compileapp.py", line 563, in run_models_in
    restricted(ccode, environment, layer=model)
  File "C:\Users\marc\Desktop\web2py\gluon\restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "C:/Users/marc/Desktop/web2py/applications/welcome/models/db.py", line 27, in <module>
    configuration = AppConfig(reload=True)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marc\Desktop\web2py\gluon\contrib\appconfig.py", line 44, in AppConfig
    setattr(AppConfig, instance_name, AppConfigLoader(*args, **vars))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marc\Desktop\web2py\gluon\contrib\appconfig.py", line 120, in __init__
    self.read_config()
  File "C:\Users\marc\Desktop\web2py\gluon\contrib\appconfig.py", line 141, in read_config
    raise BaseException("Unsupported config file format")
BaseException: Unsupported config file format
```
I tried to change the SafeConfigParser to ConfigParser and it works.

---

Furthermore, on the web2py console I got the following messages:
```
web2py Web Framework
Created by Massimo Di Pierro, Copyright 2007-2023
Version 2.25.1-stable+timestamp.2023.10.08.18.44.43
Database drivers available: sqlite3, imaplib, pymysql, pyodbc
WARNING:web2py:GUI not available because Tk library is not installed
choose a password:

please visit:
        http://127.0.0.1:8000/
use "taskkill /f /pid 3572" to shutdown the web2py server


C:\Users\marc\Desktop\web2py\applications\admin\controllers/default.py:233: SyntaxWarning: invalid escape sequence '\w'
  if not re.compile('^\w+$').match(value):
C:\Users\marc\Desktop\web2py\applications\admin\controllers/default.py:324: SyntaxWarning: invalid escape sequence '\w'
  regex = re.compile('^\w+$')
C:\Users\marc\Desktop\web2py\applications\admin\controllers/default.py:344: SyntaxWarning: invalid escape sequence '\['
  regex = re.compile('\[(.*?)\][^\:]+\:\s+(\-?\d+)')
C:\Users\marc\Desktop\web2py\applications\admin\controllers/default.py:612: SyntaxWarning: invalid escape sequence '\.'
  file = '.*\.py'
```
...and a long list of similar warnings.

I found a solution in the python 3.12 documentation: use a raw string to specify the regex.
Source: The second bullet point under https://docs.python.org/3/whatsnew/3.12.html#other-language-changes 
Example: `re.compile('^\w+$').match(value)` -> `re.compile(r'^\w+$').match(value)`

**Desktop**
- web2py (2.25.1)
- Python 3.12.0
- Windows 10

**Comment by dmatic** [comment]
The same error happens with python 3.11.5 also

**Comment by lulunac27a** [comment]
I also get the same error when I try the spreadsheet example.

**Comment by nicozanf** [comment]
It's resolved, please confirm and close the issue

**Comment by lulunac27a** [comment]
I get en error while running `web2py`:
```
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
WARNING:google.auth._default:Authentication failed using Compute Engine authentication due to unavailable metadata server.
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 64] Host is down
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 64] Host is down
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
WARNING:google.auth._default:Authentication failed using Compute Engine authentication due to unavailable metadata server.
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 64] Host is down
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 64] Host is down
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
WARNING:google.auth._default:Authentication failed using Compute Engine authentication due to unavailable metadata server.
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 64] Host is down
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 64] Host is down
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
WARNING:google.auth._default:Authentication failed using Compute Engine authentication due to unavailable metadata server.
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 64] Host is down
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 64] Host is down
WARNING:google.auth.compute_engine._metadata:Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
WARNING:google.auth._default:Authentication failed using Compute Engine authentication due to unavailable metadata server.
```

**Comment by lulunac27a** [comment]
Another error message when importing `py2web` or `yatl`:
```
Traceback (most recent call last):
  File "/Users/lucasnaceri/opt/anaconda3/lib/python3.9/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: dlopen(/Users/lucasnaceri/opt/anaconda3/lib/python3.9/site-packages/MySQLdb/_mysql.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_mysql_affected_rows'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lucasnaceri/.local/lib/python3.9/site-packages/yatl/__init__.py", line 4, in <module>
    from .template import *
  File "/Users/lucasnaceri/.local/lib/python3.9/site-packages/yatl/template.py", line 65, in <module>
    from gluon.globals import current
  File "/Users/lucasnaceri/web2py/gluon/__init__.py", line 148, in <module>
    import_packages()
  File "/Users/lucasnaceri/web2py/gluon/__init__.py", line 143, in import_packages
    sys.modules[package] = builtins.__import__(package)
  File "/Users/lucasnaceri/.local/lib/python3.9/site-packages/pydal/__init__.py", line 3, in <module>
    from .base import DAL
  File "/Users/lucasnaceri/.local/lib/python3.9/site-packages/pydal/base.py", line 150, in <module>
    from .adapters.base import BaseAdapter, NullAdapter
  File "/Users/lucasnaceri/.local/lib/python3.9/site-packages/pydal/adapters/__init__.py", line 79, in <module>
    from .google import GoogleSQL
  File "/Users/lucasnaceri/.local/lib/python3.9/site-packages/pydal/adapters/google.py", line 14, in <module>
    from .postgres import PostgrePsyco
  File "/Users/lucasnaceri/.local/lib/python3.9/site-packages/pydal/adapters/postgres.py", line 6, in <module>
    from ..drivers import psycopg2_adapt
  File "/Users/lucasnaceri/.local/lib/python3.9/site-packages/pydal/drivers.py", line 45, in <module>
    import MySQLdb
  File "/Users/lucasnaceri/opt/anaconda3/lib/python3.9/site-packages/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__
NameError: name '_mysql' is not defined
```

**Comment by nicozanf** [comment]
I think these problems are not present in the current 3.0.11 version of web2py. Can you check it on a new standard installation?

**Comment by lulunac27a** [comment]
Still get the same error

**Comment by nicozanf** [comment]
I think this is not a real problem. New standard installation of web2py with python 3.12 (with the required new versions of rocket3, pydal and yatl) has no problem like what you've described. BTW, the 'imp' module dependency was removed more than 1 year ago.
Please test it again with a new new installation, possibly a standard one without anaconda. If you still have a problem, please report the python, web2py, rocket3, pydal and yatl versions.

**Comment by lulunac27a** [comment]
```
ImportError: cannot import name 'utcnow' from 'pydal.utils' (/Users/lulu/Library/Python/3.12/lib/python/site-packages/pydal/utils.py)
```

**Comment by lulunac27a** [comment]
Versions of these modules:
```
rocket3                   20231022.2
pydal                     20231114.3
yatl                      20230507.3
python 3.12
web2py 2.19.1
```

**Comment by nicozanf** [comment]
[lulunac27a](https://github.com/lulunac27a),
you have an old web2py version (2.19.1 is dated March 2020, where there was not even Python 3.9.0 !).

You need the latest web2py (3.0.11) + the updated versions of the required modules (rocket3, pydal and yatl) in order to be compatible with python 3.12.

**Comment by lulunac27a** [comment]
It works now on Python 3.12

**Comment by leonelcamara** [comment]
Closing as it's fixed
