### ISSUE TITLE
Invoking sql queries from threads results in error

### ISSUE THREAD

**Issue by zilakmarian** [web2py/web2py#1790]
I've switched to newer version (2.15.4-stable) and found out that my code for retrieving data from database does not work anymore. It crashes on invoking 'executesql' from thread with error:
`AttributeError: 'thread._local' object has no attribute '_pydal_connection_139988697348176_13906'`

Invoking queries from main thread works correctly, this happens only calling it from threads.
Sample code:
```import threading
from gluon import current

class runSQL(threading.Thread):
	def __init__(self, sql, db_node):
		super(runSQL, self).__init__()
		self.sql = sql
		self.db_node = db_node

	def run(self):
		print "THREAD RESULT:", self.db_node.executesql(self.sql)
		
def test():
	db_nodes = current.data_nodes
	sql = "SELECT 1"
	
	threads = []
	for db in db_nodes:
		print "MAIN RESULT:", db.executesql(sql)
		
		new_thread = runSQL(sql, db)
		threads.append(new_thread)
		new_thread.start()
		
	for t in threads:
		t.join()
```
Where data_nodes are DAL objects connecting to postgres database.

That same code worked correctly on version 2.14.6-stable. Am i doing something wrong, is there a new way to run sql queries in threads? Or can anyone confirm this as a bug?
Thanks.
