### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by dburba** [web2py/web2py#1820]
Version 2.16.1-stable+timestamp.2017.11.14.05.54.25
```
def joint_field(db, fields=[]):
    e = Expression(db, db._adapter.dialect.concat(*fields[:2]))
    for f in fields[2:]:
        e = Expression(db, db._adapter.dialect.concat(e, f))
    return e
```
```
full_name_field = joint_field(db, [db.staff_employee.first_name, ' ', db.staff_employee.last_name])
records = db(full_name_field.contains(request.vars.term)).select(
    full_name_field,
    groupby=full_name_field,
    orderby=full_name_field,
    limitby=(0, 10)
)
```
```
Traceback (most recent call last):
  File "/vagrant/grand3/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/vagrant/grand3/web2py/applications/app/controllers/staff.py", line 286, in <module>
  File "/vagrant/grand3/web2py/gluon/globals.py", line 419, in <lambda>
    self._caller = lambda f: f()
  File "/vagrant/grand3/web2py/gluon/tools.py", line 3982, in f
    return action(*a, **b)
  File "/vagrant/grand3/web2py/applications/app/controllers/staff.py", line 48, in autocomplete_employee_full_name
    records = db(full_name_field.contains(request.vars.term)).select(
  File "/vagrant/grand3/web2py/gluon/packages/dal/pydal/objects.py", line 1457, in contains
    self.type.startswith('list:'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
Was working with version 2.14, not sure about 2.15

**Comment by AlighaThor** [comment]
Is that exception generated while using SQLForm.grid or smartgrid?

**Comment by dburba** [comment]
It is not grid nor smartgrid, just simple query.

**Comment by ilvalle** [comment]
@dburba can you isolate the issue running pydal only library? which is the last pydal version working?

**Comment by dburba** [comment]
Sorry for being so late. The last correctly working pyDAL version is 16.03.

**Comment by ilvalle** [comment]
I tried to write a script to run `git bisect` but there is something to review before, the following
```
from pydal import DAL, Field
from pydal.objects import Expression
db = DAL('sqlite://storage.db')
db.define_table('staff_employee', 
  Field('first_name'),
  Field('last_name'))

def joint_field(db, fields=[]):
    e = Expression(db, db._adapter.dialect.concat(*fields[:2]))
    for f in fields[2:]:
        e = Expression(db, db._adapter.dialect.concat(e, f))
    return e

full_name_field = joint_field(db, [db.staff_employee.first_name, ' ', db.staff_employee.last_name])
records = db(full_name_field.contains(request.vars.term)).select(
    full_name_field,
    groupby=full_name_field,
    orderby=full_name_field,
    limitby=(0, 10)
)
```
doesn't work with pydal v16.03, I got
```
Traceback (most recent call last):
  File "issue_1820.py", line 16, in <module>
    full_name_field = joint_field(db, [db.staff_employee.first_name, ' ', db.staff_employee.last_name])
  File "issue_1820.py", line 11, in joint_field
    e = Expression(db, db._adapter.dialect.concat(*fields[:2]))
AttributeError: 'SQLiteAdapter' object has no attribute 'dialect'
```
How did you test it worked with 16.03?

**Comment by dburba** [comment]
I tired with PostgreSQL, not SQLite. Moreover I have application with the same snippet running on  Version 2.14.6-stable+timestamp.2016.05.10.00.21.47 (with pyDAL 16.03), but...
Sorry, I am really fool...
Initial code working with pyDAL 16.03 is:
```
def joint_field(db, fields=[]):
    e = Expression(db, db._adapter.CONCAT, *fields[:2])
    for f in fields[2:]:
        e = Expression(db, db._adapter.CONCAT, e, f)
    return e
```
Now I see that I buggy ported it for newer pyDAL, it should be:
```
def joint_field(db, fields=[]):
    e = Expression(db, db._adapter.dialect.concat, *fields[:2])
    for f in fields[2:]:
        e = Expression(db, db._adapter.dialect.concat, e, f)
    return e
```
Sorry for all your wasted time, it is my shameful mistake. Issue closed.
